### PR TITLE
fix: refactor default export for useKBar

### PR DESCRIPTION
**Pull request by kevinhu**
The default export for `useKBar` causes build issues when using Vite (#85). This can be mitigated by switching it to a named export.

### CODE REVIEW

**Comment by timc1** [comment]
Hey @kevinhu, thanks for looking into this! If possible, it would be great to migrate [the other default exports](https://github.com/timc1/kbar/blob/08cf690d93b731ef4f148c6ad154d3f8223eb8e8/src/index.tsx#L1-L8) in this PR if you would like to take that on – probably good to keep things consistent, we can have something like:

```tsx
import { createAction } from "./utils";
export { createAction };

export * from "./useMatches";
export * from "./KBarPortal";
export * from "./KBarPositioner";
export * from "./KBarSearch";
export * from "./KBarResults";
export * from "./useKBar";
export * from "./useRegisterActions";
export * from "./KBarContextProvider";
export * from "./KBarAnimator";
export * from "./types";
export * from "./action";

```

**Comment by kevinhu** [comment]
No problem, done!

**Review by timc1 — CHANGES_REQUESTED** [review]
Missing an export: https://github.com/timc1/kbar/blob/bc35f63895634518a3958806771dafdec5d2d2f7/example/src/hooks/useThemeActions.tsx#L1

👇 

```
import { useRegisterActions } from "../../../src/useRegisterActions";
```

**Comment by kevinhu** [comment]
Fixed

**Comment by evcohen** [comment]
thank you!

**Pull request merged**
