### PR TITLE
feat: add toggle shortcut option and support tinykey keybindings

### LINKED ISSUE #55: Allow Developers to Configure Keyboard Shortcut (Instead of Cmd+K)
It may be nice to allow developers to pass in their own custom keyboard shortcut to instantiate kbar if they didn't want to use the preconfigured cmd+k. Some apps for example use cmd+/. Others use cmd+shift+P.

### PR DESCRIPTION
**Pull request by avigoldman**
Closes #55 and #121

### CODE REVIEW

**Comment by avigoldman** [comment]
There seems to be an issue with tinykeys not supporting special characters like `?`. I did PR as a first pass to fix that issue here. https://github.com/jamiebuilds/tinykeys/pull/131

**Comment by smhutch** [comment]
@avigoldman @timc1 is there anything I could do to help with this PR? I'm working on a code editor, meaning we can't really use single character keyboard shortcuts (since we focus the editor in most cases 😄)

I would be happy to dedicate some time towards adding support for combinations like `CMD + 1` or `Ctrl + x` etc. Any particular place I could help out here?

**Comment by timc1** [comment]
Hey @smhutch, we can get rid of the `event.metaKey` check [here](https://github.com/timc1/kbar/blob/fd73c15ffe25a9a8e8846ac25c142f5783fc4d12/src/InternalEvents.tsx#L160) in the current implementation to get cmd/ctrl to work properly; however, we would need to add a few additional safeguards against registering cmd/ctrl+k. 

I think it should be pretty straight forward; we originally added the `event.metaKey` as more of an easy solution. If you want to take a stab at removing it that would be great – I'll look into a solution as well tomorrow.

**Comment by timc1** [comment]
Closed as part of #185

**Pull request closed without merging**
